smtp:
    address: smtp.gmail.com
    port: 587
    user_name: <USERNAME>
    domain: gmail.com
    password: <PASSWORD>
    authentication: plain
    enable_starttls_auto: true
pop3:
    address: pop.gmail.com
    port: 995
    user_name: <USERNAME>
    password: <PASSWORD>
    enable_ssl: true
